version: '3.7'

services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports: 
      - 8088:8080
    networks:
      - monitor-net
    restart: unless-stopped

networks:
  monitor-net:
    name: monitor-net
    driver: bridge

